Add pages for reopenInvestigation and taskComplete
demisto/content-docs pull request #1015
Opened 2022-03-06 08:43 UTC by tschanfeld

Requested here https://github.com/demisto/etc/issues/45988 to be included in the builtins section of xsoar.pan.dev below Get Entries Filter topic. Includes info from script helper as well as info about basic use cases.

## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

2022-03-09 04:32 UTC, ali-sawyer requested changes
`reopenInvestigation` looks good. Please fix the description for `taskComplete`. Thanks!

2022-03-09 04:32 UTC, ali-sawyer commented on docs/integrations/task-complete.md
> +
Looks like the wrong description (the one for `reopenInvestigation`) got copied here.

2022-03-10 16:09 UTC, ali-sawyer approved these changes
Looks good!

2022-03-13 08:15 UTC, tschanfeld commented
@ali-sawyer Can you tell what went wrong here?  ci/circleci: build — Your tests failed on CircleCI

2022-03-14 23:16 UTC, ali-sawyer commented
There was an error with some code CircleCI runs, unrelated to the change we made. A rerun might fix it but I don't have permissions to do so. 

![Screen Shot 2022-03-14 at 5 14 19 PM](https://user-images.githubusercontent.com/91506078/158275942-b6021bb0-c928-4f9e-a5ed-7fc75a2a7e1e.png)
![Screen Shot 2022-03-14 at 5 14 38 PM](https://user-images.githubusercontent.com/91506078/158275965-d26e0c02-4463-4673-b3be-72ec163bb64d.png)

Do you know who on the Engineering side administrates CircleCI?

2022-03-15 06:34 UTC, tschanfeld commented
@ShahafBenYakir Can you assist?

2022-03-16 08:50 UTC, ChanochShayner commented
@MosheEichler fyi

2022-03-16 09:26 UTC, merged