update_approved_tags_usecases
demisto/content-docs pull request #1259
Opened 2022-12-26 13:25 UTC by bakatzir

## Status
Ready

2022-12-26 14:33 UTC, edik24 commented
@bakatzir check the preview - the lists are duplicated

2022-12-27 08:17 UTC, edik24 requested changes

2022-12-27 08:17 UTC, edik24 commented on docs/documentation/pack-docs.md
>  - ***Use-case*** -- a name of a situation in which packs can be used - usually the pack name. The optional approved values for use-cases are:
I'm not sure how the current list is done - but if you check the preview, there are 2 lists now here and in tags

2022-12-27 09:57 UTC, bakatzir commented
The approved_usecases and approved_tags are being rendered automatically, see details in this PR: https://github.com/demisto/content-docs/pull/382

Hence, we will just need to update the approved lists in the content repo, and it will update in xsoar pan dev automatically.

2022-12-27 09:57 UTC, closed without merging