Configurations Sections
demisto/content-docs pull request #1558
Opened 2024-05-29 11:22 UTC by RotemAmit

## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
I added an explanation about the different possible sections in the integration configuration.

## Screenshots
Paste here any images that will help the reviewer

2024-05-29 11:42 UTC, BEAdi requested changes
Great work!
I think we should add all of the connect and collect params from the guideline document, so contributors will most likely find what they are looking for here and won't have to ask.

2024-05-29 11:42 UTC, BEAdi commented on docs/integrations/yaml-file.md
> +1. Add the `sectionorder` key to the yml's root. This key should contain a list of sections available. Currently we support only "Connect",  "Collect" and "Optimize".
```suggestion
1. Add the `sectionOrder` key to the yml's root. This key should contain a list of sections available. Currently we support only "Connect",  "Collect" and "Optimize".
```
We use it in content this way

2024-05-29 11:42 UTC, BEAdi commented on docs/integrations/yaml-file.md
> +3. If the parameter is to be shown only as part of the advanced settings in the section, add the advanced key with value set to true.
```suggestion
3. If the parameter is to be shown only as part of the advanced settings in the section, add the `advanced: true` key and value to it.
```

2024-05-29 11:42 UTC, BEAdi commented on docs/integrations/yaml-file.md
> +```yml
```suggestion
For example:
```yml
```

2024-05-29 11:42 UTC, BEAdi commented on docs/integrations/yaml-file.md
> +The sections will look like this in the UI (advanced parameters are hidden unless opening the Advanced Settings  section):
```suggestion
The sections will look like this in the UI, when advanced parameters are hidden unless opening the `Advanced Settings` section:
```

2024-05-30 08:40 UTC, BEAdi approved these changes
Great!

2024-05-30 08:40 UTC, BEAdi commented on docs/integrations/yaml-file.md
> +  - Bypass exclusion list
```suggestion
  - Indicator expiration method
  - Feed fetch interval
  - Bypass exclusion list
  - Create relationships
  - Any additional filters / Non mandatory parameters
```
`Bypass exclusion list` was written twice

2024-05-30 08:40 UTC, BEAdi commented on docs/integrations/yaml-file.md
> +  - Run on Single engine
```suggestion
  - Trust any certificate (not secure)
  - Use system proxy settings
  - Log level
  - Run on single engine
  - Any additional filters / Non mandatory parameters
```

2024-05-30 12:17 UTC, ShirleyDenkberg commented on docs/integrations/yaml-file.md
> +As of XSOAR version 8.1 and XSIAM version 1.3, integration's configuration display is divided to sections to help our users configure the instances.
```suggestion
As of Cortex XSOAR version 8.1 and Cortex XSIAM version 1.3, an integration's configuration display is divided to sections to help our users configure the instances.
```

2024-05-30 12:17 UTC, ShirleyDenkberg commented on docs/integrations/yaml-file.md
> +In the advanced section should be parameters that are part of advanced usage of the integration.
```suggestion
The Advanced section should contain parameters that are part of advanced usage of the integration.
```

2024-05-30 12:17 UTC, ShirleyDenkberg commented on docs/integrations/yaml-file.md
> +In the Connect section should be parameters that the customer needs to configure in order to connect to the product.
```suggestion
The Connect section should contain parameters that the customer needs to configure in order to connect to the product. 
```

2024-05-30 12:17 UTC, ShirleyDenkberg commented on docs/integrations/yaml-file.md
> +- Connect Prams:
```suggestion
- Connect Parameters:
```

2024-05-30 12:17 UTC, ShirleyDenkberg commented on docs/integrations/yaml-file.md
> +- Advanced Connect Params:
```suggestion
- Advanced Connect Parameters:
```

2024-05-30 12:17 UTC, ShirleyDenkberg commented on docs/integrations/yaml-file.md
> +In the Collect section should be parameters that the customer needs to configure in order to collect information from the product.
```suggestion
The Collect section should contain parameters that the customer needs to configure in order to collect information from the product.
```

2024-05-30 12:17 UTC, ShirleyDenkberg commented on docs/integrations/yaml-file.md
> +- Collect Params:
```suggestion
- Collect Parameters:
```

2024-05-30 12:17 UTC, ShirleyDenkberg commented on docs/integrations/yaml-file.md
> +- Advanced Collect Params:
```suggestion
- Advanced Collect Parameters:
```

2024-05-30 12:17 UTC, ShirleyDenkberg commented on docs/integrations/yaml-file.md
> +The Optimize Params are params that are less fit to be in connect or collect section, e.g: Advanced Thresholds, Advanced Queries.
```suggestion
The Optimize Parameters are parameters that do not belong in the Connect or Collect sections, e.g., Advanced Thresholds, Advanced Queries.
```

2024-05-30 12:17 UTC, ShirleyDenkberg commented on docs/integrations/yaml-file.md
> +In order to add sections to your integration, follow this guide:
```suggestion
To add sections to your integration:
```

2024-05-30 12:18 UTC, ShirleyDenkberg commented
@BEAdi Doc review completed.

2024-05-30 13:32 UTC, merged