Update aws-auth-guide.md
demisto/content-docs pull request #321
Opened 2020-10-04 06:21 UTC by ShirleyDenkberg

Edited the content based on comments in https://github.com/demisto/etc/issues/27179

## Status
Ready

## Related Issues
fixes: link to the issue

## Description
See comments in https://github.com/demisto/etc/issues/27179

## Screenshots
Paste here any images that will help the reviewer

2020-10-07 23:28 UTC, glicht commented on content-repo/extra-docs/articles/aws-auth-guide.md
> +The following describes the EC2 instance metadata use case.
Not correct. STS can be used in both EC2 and access key scenarios. Please delete this line.

2020-10-07 23:33 UTC, glicht requested changes
Need to move `Prerequisites` to be under: `How XSOAR uses STS to Authenticate`.

2020-10-15 06:11 UTC, fvigo commented
@ShirleyDenkberg when you get a chance could you please handle the change Guy suggested, so we can merge it? thanks in advance!

2020-11-01 17:57 UTC, glicht commented
@ShirleyDenkberg what's the status here?

2020-11-01 18:01 UTC, glicht approved these changes
I see you added a commit. Looks good.

2020-11-01 18:01 UTC, merged