Generic IAM commands documentation
demisto/content-docs pull request #427
Opened 2021-01-04 14:15 UTC by Arsenikr

## Status
In Progress

## Description
Documentation of the generic IAM commands

2021-01-05 13:41 UTC, dantavori requested changes
looks good 👍🏽

2021-01-05 13:41 UTC, dantavori commented on docs/integrations/generic-commands-iam.md
> +In order to properly map between the generic IAM user fields and the data from the integration, we need to define an incoming [Mapper](../incidents/incident-classification-mapping#map-event-attribute
incoming for get-user, outgoing for update/create.
I think this is also the place to explain that their names should be the default values for "mapper-in" and "mapper-out" parameters.

2021-01-05 13:41 UTC, dantavori commented on docs/integrations/generic-commands-iam.md
> +  "IAM.Vendor.": {
```suggestion
  "IAM.Vendor": {
```

2021-01-05 13:41 UTC, dantavori commented on docs/integrations/generic-commands-iam.md
> +      "Zoom Payload can go as is here in json format": ""
```suggestion
    "id": "Unique Id here",
    "username": "demistotest@paloaltonetworks.com",
    "email": "demistotest@paloaltonetworks.com",
    "errorCode": "null for success response",
    "errorMessage": "null for success response",
    "details": {
      "Payload from vendor can go as is here in json format": ""
```

2021-01-08 09:57 UTC, anara123 requested changes
Overall there are a lot of details missing from the doc. New partner/developer should be able to read the doc and be able to develop new IAM integration from scratch

2021-01-08 09:57 UTC, anara123 commented on docs/integrations/generic-commands-iam.md
> +IAM integrations generally do not support CRUD (Create, Retrieve, Update, and Disable/Delete) operations for general user accounts or provisioning users. These integrations should adhere to a standar
```suggestion
IAM integrations generally support CRUD (Create, Retrieve, Update, and Disable/Delete) operations for general user accounts or provisioning users. These integrations should adhere to a standard as the workflows can be generalized or completely customized to fit into an organization's environment.
```

2021-01-08 09:57 UTC, anara123 commented on docs/integrations/generic-commands-iam.md
> +The mapper names should be the default values for "mapper-in" and "mapper-out" parameters of the inegration instance.
```suggestion
The mapper names should be the default values for "mapper-in" and "mapper-out" parameters of the integration instance. 
```

2021-01-08 09:57 UTC, anara123 commented on docs/integrations/generic-commands-iam.md
> +For integrations that support the [SCIM](http://www.simplecloud.info/) protcol, you can use the built in SCIM mappers in the IAM-SCIM pack.
```suggestion
For integrations that support the [SCIM](http://www.simplecloud.info/) protocol, you can use the built in SCIM mappers in the IAM-SCIM pack.  
```

2021-01-08 09:57 UTC, anara123 commented on docs/integrations/generic-commands-iam.md
> +## **iam-create-user**
```suggestion
### **iam-create-user**
```

2021-01-08 09:57 UTC, anara123 commented on docs/integrations/generic-commands-iam.md
> +## **update-user**
```suggestion
### **update-user**
```

2021-01-08 09:57 UTC, anara123 commented on docs/integrations/generic-commands-iam.md
> +## **iam-disable-user**
```suggestion
### **iam-disable-user**
```

2021-01-08 09:57 UTC, anara123 commented on docs/integrations/generic-commands-iam.md
> +[ServiceNow](https://github.com/demisto/content/tree/master/Packs/ServiceNow/Integrations/ServiceNow_IAM)
```suggestion
[HelloIAMWorld](https://github.com/demisto/content/tree/master/Packs/HelloIAMWorld/Integrations/HelloIAMWorld)  
[Okta](https://github.com/demisto/content/tree/master/Packs/Okta/Integrations/Okta_IAM)  
[ServiceNow](https://github.com/demisto/content/tree/master/Packs/ServiceNow/Integrations/ServiceNow_IAM) 
 ```

2021-01-08 09:57 UTC, anara123 commented on docs/integrations/generic-commands-iam.md
> +**Description:** creates a user
Creates a user, and if user exits then updates the user. If user exits but disabled, then enable the user.

2021-01-08 09:57 UTC, anara123 commented on docs/integrations/generic-commands-iam.md
> +```json
all the commands also return `IAM.UserProfile` object

2021-04-01 13:48 UTC, glicht commented
@Arsenikr where are we with this?

2021-04-01 14:51 UTC, Arsenikr commented
@dantavori took responsibility on it from me because it is a technical docs

2021-04-04 14:51 UTC, closed without merging