IAM changes add SCIM
demisto/content-docs pull request #428
Opened 2021-01-04 15:46 UTC by ohaim1008

## Status
[ ] Ready
[x] In Progress

## Related Issues
Related to: demisto/etc#31369

## Description
GIthub IAM is using the mappers that are in IAM-SCIM pack,
later on we expect that more integration will use those mappers.

2021-01-04 17:33 UTC, idovandijk requested changes
There are additional places where we need to edit:
![image](https://user-images.githubusercontent.com/43602124/103562204-5e24ee80-4ec3-11eb-8f61-b546668fbf9f.png)

![image](https://user-images.githubusercontent.com/43602124/103562271-798ff980-4ec3-11eb-8343-822140dc7183.png)


I suggest to quickly go over the sections in
https://xsoar.pan.dev/docs/reference/articles/identity-lifecycle-management

and see if there's something special that GitHub requires (like configuration for example).
See these sections on the right
![image](https://user-images.githubusercontent.com/43602124/103562429-be1b9500-4ec3-11eb-9321-dca765298a1f.png)

2021-01-13 10:03 UTC, ohaim1008 commented
@ShirleyDenkberg Hi Shirley can you please review those changes?

2021-01-14 13:16 UTC, ShirleyDenkberg commented
@idovandijk Doc review completed.

2021-01-14 15:44 UTC, idovandijk approved these changes

2021-01-14 15:45 UTC, merged