adding to repo
demisto/content-docs pull request #531
Opened 2021-03-11 08:31 UTC by tschanfeld

## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

2021-03-15 09:31 UTC, fvigo commented
@tschanfeld is it ready for review? If so please assign a reviewer! Thanks!

2021-03-15 16:43 UTC, glicht requested changes
Please add a note mentioning that for Python integrations there is need to follow the instructions at: https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-1/cortex-xsoar-admin/docker/configure-python-docker-integrations-to-trust-custom-certificates.html

2021-03-15 16:43 UTC, glicht commented on content-repo/extra-docs/articles/trust-custom-certificates.md
> +2. Reboot the server.
Better to use restart. If you have a link with instructions, would be nice to add this here too.
```suggestion
2. Restart the Server.
```

2021-03-15 16:45 UTC, glicht commented on content-repo/extra-docs/articles/trust-custom-certificates.md
> +2. Reboot the server.
Also mention that the Engine requires a restart after this configuration change.

2021-03-16 13:25 UTC, glicht commented
@tschanfeld can you go over the formatting. The bullets don't look good:

![image](https://user-images.githubusercontent.com/1395797/111316297-d0584300-866b-11eb-839b-6fd70e715b4d.png)

2021-03-21 06:29 UTC, tschanfeld reviewed
@glicht Is this approved (removed bulleted list)?

2021-03-21 08:53 UTC, glicht approved these changes

2021-03-22 11:52 UTC, kirbles19 commented
@glicht Done with the review, ready to merge

2021-03-22 13:04 UTC, kirbles19 approved these changes

2021-03-29 06:31 UTC, tschanfeld commented
@kirbles19  Can someone squash/merge if this is ready to go?

2021-03-29 07:08 UTC, merged

2021-03-29 07:08 UTC, fvigo commented
@tschanfeld done