Marketplace pictures slideshow
demisto/content-docs pull request #764
Opened 2021-08-19 09:50 UTC by daryakoval

## Status
Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/39373

## Description
Add three banners in the marketplace page in xsoar.pan.dev,
under the filter bar as a slideshow, each link to other site.

## Screenshots
![image](https://user-images.githubusercontent.com/72339940/130047906-462fd12e-8ff2-4f60-9e31-08fcc13e0025.png)

2021-08-22 12:33 UTC, daryakoval commented
TODO: check if we need remove scroller near the pictures.

2021-08-24 17:48 UTC, dantavori approved these changes

2021-08-24 17:48 UTC, dantavori reviewed
please remove the .demisto-sdk.report file

2021-08-25 12:04 UTC, glicht commented on .demisto-sdk-report
> +[]
Please remove this file

2021-08-25 12:14 UTC, glicht requested changes

2021-08-25 12:14 UTC, glicht commented on src/pages/marketplace/slideshow.js
> +    url: 'https://raw.githubusercontent.com/demisto/content-docs/148c5a9e7153b1688acb2f331b414e30a3f75f8c/src/pages/marketplace/images/Marketplace_Vertical_1.png',
Link to the images with relative links and not via the `raw.github..` link. The images should go into the `static/img` dir. You can open there a subdir and put all related images to the sliideshow.

2021-09-05 06:58 UTC, glicht approved these changes
Looks good

2021-09-05 09:24 UTC, merged