Private Offer Updates.md
demisto/content-docs pull request #897
Opened 2021-12-27 04:54 UTC by marcellarichmond

## Status
In Progress

## Related Issues
fixes: link to the issue

## Description
Updating several pages for private offer launch. 

## Screenshots
Paste here any images that will help the reviewer

2021-12-27 05:11 UTC, marcellarichmond commented
Not ready to be reviewed and listed yet. More changes to be made.

2021-12-29 02:08 UTC, mchasepan reviewed
Looking GREAT @marcellarichmond !!!!

2021-12-29 02:08 UTC, mchasepan commented on docs/partners/private-offer.md
> +For Partners interested in having their premium content available for Private Offer on the XSOAR Marketplace, please contact the XSOAR Partner Success Team (PST) at __xsoar.privateoffer@paloaltonetwo
fix link

2021-12-29 02:08 UTC, mchasepan commented on docs/partners/private-offer.md
> +  <summary>Click here for detailed steps to add Private Offer to a Content Pack</summary>
@ShahafBenYakir this doenst look right in the preview

2021-12-29 02:08 UTC, mchasepan commented on docs/partners/private-offer.md
> +Contact __xsoar.privateoffer@paloaltonetworks.com__ for help.
fix link

2021-12-29 02:08 UTC, mchasepan commented on docs/partners/private-offer.md
> +**Have a Private Offer Opportunity?** Please email the details of the request to: __xsoar.privateoffer@paloaltoneworks.com__.
fix link

2021-12-29 02:08 UTC, mchasepan commented on docs/partners/private-offer.md
> +The Agreement details the terms and conditions for delivering Partner content to a specific Customer through the XSOAR Marketplace. The Agreement represents a binding contract between the Partner and
```suggestion
The Agreement details the terms and conditions for delivering Partner content to a specific Customer through the XSOAR Marketplace. The Agreement represents a binding contract between the Partner and Palo Alto Networks ([see sample](../doc_imgs/partners/PrivateOfferTermsAgreementSample.pdf)).
```

2021-12-29 02:08 UTC, mchasepan commented on docs/partners/private-offer.md
> +* Write a blog post [template here](https://docs.google.com/document/d/1amTRiQ2fl_wUNvfF8M4MP939PlK2x-nyCQLqzjsV_eg/edit?usp=sharing)
```suggestion
* Write a blog post [template here](https://docs.google.com/document/d/1amTRiQ2fl_wUNvfF8M4MP939PlK2x-nyCQLqzjsV_eg/edit?usp=sharing) (must adhere to Palo Alto Networks branding and logo [usage guidelines](https://www.paloaltonetworks.com/company/brand.html))
```

2021-12-29 02:08 UTC, mchasepan commented on docs/partners/private-offer.md
> +*must adhere to Palo Alto Networks branding and logo [usage guidelines](https://www.paloaltonetworks.com/company/brand.html).
```suggestion
```

2021-12-29 02:08 UTC, mchasepan commented on docs/partners/private-offer.md
> +For more information about Private Offer, please review our [Partner FAQ](https://docs.google.com/document/d/1kUFQPKmuiJuFHNtrg6RHg4cEMeAkjGsDNPXK9Etf4eY/edit#heading=h.pe5n8bsuhdc)(restricted access
```suggestion
For more information about Private Offer, please review our [Partner FAQ](https://docs.google.com/document/d/1kUFQPKmuiJuFHNtrg6RHg4cEMeAkjGsDNPXK9Etf4eY/edit#heading=h.pe5n8bsuhdc) (restricted access). For questions or help, please contact the [Partner Success Team](mailto:xsoar.privateoffer@paloaltonetworks.com). 
```

2021-12-29 22:08 UTC, MMCrosby approved these changes

2021-12-29 22:08 UTC, MMCrosby commented on docs/partners/private-offer.md
> +* Include Cortex XSOAR in your materials
```suggestion
* Highlight the value prop of your Cortex XSOAR solution and partnership on your website
```

2021-12-29 22:08 UTC, MMCrosby commented on docs/partners/private-offer.md
> +
```suggestion
*  Get the word out to your customers (see email template)
* Do a webinar
* Post about it on LinkedIn

```

2021-12-30 01:52 UTC, mchasepan commented on docs/partners/private-offer.md
> +**Have a Private Offer Opportunity?** Please email the details of the request to xsoar.privateoffer@paloaltoneworks.com.
```suggestion
**Have a Private Offer Opportunity?** Please email the details of the request to xsoar.privateoffer@paloaltonetworks.com.
```

2021-12-30 01:56 UTC, mchasepan commented on docs/partners/private-offer.md
> +[Learn about private offer](https://xsoar.pan.dev/private-offer-learn-more)
```suggestion
[Learn about Private Offer](https://xsoar.pan.dev/private-offer-learn-more)
```

2021-12-30 14:29 UTC, MMCrosby requested changes

2021-12-30 14:29 UTC, MMCrosby commented on docs/partners/premium-packs-process.md
> +To update your Premium Pack to be available through Private Offer, please follow these [steps](https://xsoar.pan.dev/request-private-offer).
```suggestion
To update your Premium Pack to be available through Private Offer, please follow these [steps](https://xsoar.pan.dev/docs/partners/private-offer#private-offer-listing-designation-steps).

```

2021-12-30 18:57 UTC, MMCrosby approved these changes

2021-12-30 18:57 UTC, MMCrosby commented on docs/partners/premium-packs-process.md
> +Build the content for the premium packs. Customers can subscribe to Premium Packs on a monthly basis or through [Private Offer](https://xsoar.pan.dev/private-offer).
```suggestion
Build the content for the premium packs. Customers can subscribe to Premium Packs on a monthly basis or through [Private Offer](https://xsoar.pan.dev/docs/partners/private-offer). 

```

2021-12-30 19:29 UTC, MMCrosby approved these changes

2021-12-30 19:29 UTC, MMCrosby commented on docs/partners/marketplace.md
> +Additionally, Partners have the ability to monetize their content on the Marketplace. You decide the content, the price, and how to best market it, and get a healthy share of the revenue. The custome
```suggestion
Additionally, Partners have the ability to monetize their content on the Marketplace. You decide the content, the price, how to best market it, and get a healthy share of the revenue. The customer gets premium content to solve their use case. It's a win-win. Partners who wish to contribute premium packs must follow a few [additional onboarding steps](https://xsoar.pan.dev/docs/partners/premium-packs-process) and can now take advantage of [Private Offers](https://xsoar.pan.dev/docs/partners/private-offer)! 
```

2021-12-30 19:29 UTC, MMCrosby commented on docs/partners/marketplace.md
> +Packs on Marketplace can be free or premium. Our platform does full dependency checking too, so a pack can be dependent on, say, a command in another pack. This allows you to build a playbook address
```suggestion
Packs on Marketplace can be free or premium. Our platform does full dependency checking too, so a pack can be dependent on, say, a command in another pack. This allows you to build a playbook addressing a full use case across products. Premium packs are held in your private repository. Free packs are held in our open source repository.
```

2021-12-30 19:29 UTC, MMCrosby commented on docs/partners/marketplace.md
> +For packs that resell 3rd party products, the following illustrates the flow of subscription:
```suggestion
For packs that resell 3rd party products, the following illustrates the subscription flow:
```

2021-12-30 19:45 UTC, MMCrosby approved these changes

2021-12-30 19:45 UTC, MMCrosby commented on docs/partners/private-offer.md
> +Requests can also be initiated through your sales teams or our Cortex sales teams. We highly recommend that your teams promote your XSOAR packs to ensure customers/prospects know you have a premium o
```suggestion
Requests can also be initiated through your sales teams or our Cortex sales teams. We highly recommend that your teams promote your XSOAR packs to ensure customers/prospects know you have a premium offering in the XSOAR Marketplace. If an opportunity is identified, email the details of the request to xsoar.privateoffer@paloaltonetworks.com. 
```

2021-12-30 20:42 UTC, MMCrosby approved these changes

2021-12-30 20:42 UTC, MMCrosby commented on docs/partners/marketplace.md
> + -**Private Offer:** Customer subscribes to your premium content for a mutually agreed upon term length and price. We automatically pay you a revenue share, up front, for the full contracted term!
```suggestion
- **Private Offer:** Customer subscribes to your premium content for a mutually agreed upon term length and price. We automatically pay you a revenue share, up front, for the full contracted term!  
```

2021-12-30 21:45 UTC, merged