Slack notifier to build process
demisto/content-docs pull request #909
Opened 2022-01-03 15:54 UTC by dansterenson

## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

2022-01-16 09:12 UTC, reutshal requested changes
Looks good, please see my comments

2022-01-17 15:58 UTC, dansterenson commented on build_utils/slack_notifier.py
> +def get_circle_failed_steps(ci_token, build_number):
Done

2022-01-17 15:58 UTC, dansterenson commented on build_utils/slack_notifier.py
> +def create_slack_notifier(slack_token, build_url, failed_job_name, ci_token, build_number):
Done

2022-01-18 08:00 UTC, dansterenson commented on .circleci/config.yml
> +            if [ "$CIRCLE_BRANCH" == "master" ]; then
Done

2022-01-18 08:16 UTC, reutshal approved these changes

2022-01-23 08:19 UTC, reutshal approved these changes

2022-01-23 16:22 UTC, merged